//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parkeon.Common.Configuration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Parkeon.Common.Configuration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string ConfigurationEntry_Attribute_Name {
            get {
                return ResourceManager.GetString("ConfigurationEntry_Attribute_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSettings.xml.
        /// </summary>
        internal static string DefaultSettingsFileName {
            get {
                return ResourceManager.GetString("DefaultSettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file&apos;{0}&apos; does not exists - can not configure the {1}.
        /// </summary>
        internal static string msg_ConfigurationFileDoesNotExist {
            get {
                return ResourceManager.GetString("msg_ConfigurationFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Output error occured while loading XML configuration file &apos;{0}&apos; - file can not be read.
        /// </summary>
        internal static string msg_ConfigurationFileLoadIOError {
            get {
                return ResourceManager.GetString("msg_ConfigurationFileLoadIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while loading XML configuration file &apos;{0}&apos;.
        /// </summary>
        internal static string msg_ConfigurationFileLoadXMLError {
            get {
                return ResourceManager.GetString("msg_ConfigurationFileLoadXMLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while accessing configuration - Configuration Entry &apos;{0}&apos; does not exist in the config file &apos;{1}&apos;. Will use default value of &apos;{2}&apos;.
        /// </summary>
        internal static string msg_ConfigurationKeyDoesNotExist_UsingDefault {
            get {
                return ResourceManager.GetString("msg_ConfigurationKeyDoesNotExist_UsingDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while accessing configuration - Configuration Entry &apos;{0}&apos; does not exist in the config file.
        /// </summary>
        internal static string msg_ConfigurationKeyDoesNotExists {
            get {
                return ResourceManager.GetString("msg_ConfigurationKeyDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while accessing configuration - Configuration Entry &apos;{0}&apos; is not an appSetting.
        /// </summary>
        internal static string msg_ConfigurationKeyNotAppSetting {
            get {
                return ResourceManager.GetString("msg_ConfigurationKeyNotAppSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while accessing configuration - Configuration Entry &apos;{0}&apos; is not a Connection String.
        /// </summary>
        internal static string msg_ConfigurationKeyNotConnectionString {
            get {
                return ResourceManager.GetString("msg_ConfigurationKeyNotConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while accessing configuration - Configuration Entry &apos;{0}&apos; is not a Configuration Section.
        /// </summary>
        internal static string msg_ConfigurationKeyNotSection {
            get {
                return ResourceManager.GetString("msg_ConfigurationKeyNotSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while accessing configuration - Configuration Entry &apos;{0}&apos; is not a string value.
        /// </summary>
        internal static string msg_ConfigurationKeyNotString {
            get {
                return ResourceManager.GetString("msg_ConfigurationKeyNotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while accessing configuration - Configuration Entry &apos;{0}&apos; is duplicated in the config file &apos;{1}&apos;.
        /// </summary>
        internal static string msg_DuplicatedEntries {
            get {
                return ResourceManager.GetString("msg_DuplicatedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration node &apos;{0}&apos; must contain name attributte in the config file &apos;{1}&apos;..
        /// </summary>
        internal static string msg_NoNameAttribute {
            get {
                return ResourceManager.GetString("msg_NoNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //ConfigurationEntry.
        /// </summary>
        internal static string XPath_Select_ConfigurationEntry {
            get {
                return ResourceManager.GetString("XPath_Select_ConfigurationEntry", resourceCulture);
            }
        }
    }
}
