//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditorsTeamTV.Scheduling.Configuration
{
    
    
    /// <summary>
    /// The QuartzConfigurationSection Configuration Section.
    /// </summary>
    public partial class QuartzConfigurationSection : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the QuartzConfigurationSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string QuartzConfigurationSectionSectionName = "quartzConfigurationSection";
        
        /// <summary>
        /// Gets the QuartzConfigurationSection instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public static global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationSection Instance
        {
            get
            {
                return ((global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationSection)(global::System.Configuration.ConfigurationManager.GetSection(global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationSection.QuartzConfigurationSectionSectionName)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationSection.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationSection.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region quartzPluginSettings Property
        /// <summary>
        /// The XML name of the <see cref="quartzPluginSettings"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string quartzPluginSettingsPropertyName = "quartzPluginSettings";
        
        /// <summary>
        /// Gets or sets the quartzPluginSettings.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The quartzPluginSettings.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationSection.quartzPluginSettingsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public global::EditorsTeamTV.Scheduling.Configuration.QuartzPluginSettings quartzPluginSettings
        {
            get
            {
                return ((global::EditorsTeamTV.Scheduling.Configuration.QuartzPluginSettings)(base[global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationSection.quartzPluginSettingsPropertyName]));
            }
            set
            {
                base[global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationSection.quartzPluginSettingsPropertyName] = value;
            }
        }
        #endregion
        
        #region quartzThreadPoolSettings Property
        /// <summary>
        /// The XML name of the <see cref="quartzThreadPoolSettings"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string quartzThreadPoolSettingsPropertyName = "quartzThreadPoolSettings";
        
        /// <summary>
        /// Gets or sets the quartzThreadPoolSettings.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The quartzThreadPoolSettings.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationSection.quartzThreadPoolSettingsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public global::EditorsTeamTV.Scheduling.Configuration.QuartzThreadPoolSettings quartzThreadPoolSettings
        {
            get
            {
                return ((global::EditorsTeamTV.Scheduling.Configuration.QuartzThreadPoolSettings)(base[global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationSection.quartzThreadPoolSettingsPropertyName]));
            }
            set
            {
                base[global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationSection.quartzThreadPoolSettingsPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace EditorsTeamTV.Scheduling.Configuration
{
    
    
    /// <summary>
    /// A collection of QuartzConfigurationItem instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::EditorsTeamTV.Scheduling.Configuration.QuartzPluginSettings.QuartzConfigurationItemPropertyName)]
    public partial class QuartzPluginSettings : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string QuartzConfigurationItemPropertyName = "quartzConfigurationItem";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override string ElementName
        {
            get
            {
                return global::EditorsTeamTV.Scheduling.Configuration.QuartzPluginSettings.QuartzConfigurationItemPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::EditorsTeamTV.Scheduling.Configuration.QuartzPluginSettings.QuartzConfigurationItemPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem)(element)).Key;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem this[int index]
        {
            get
            {
                return ((global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> with the specified key.
        /// </summary>
        /// <param name="key">The key of the <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem this[object key]
        {
            get
            {
                return ((global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem)(base.BaseGet(key)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="quartzConfigurationItem">The <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public void Add(global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem quartzConfigurationItem)
        {
            base.BaseAdd(quartzConfigurationItem);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="quartzConfigurationItem">The <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public void Remove(global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem quartzConfigurationItem)
        {
            base.BaseRemove(this.GetElementKey(quartzConfigurationItem));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem GetItemAt(int index)
        {
            return ((global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> with the specified key.
        /// </summary>
        /// <param name="key">The key of the <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem GetItemByKey(string key)
        {
            return ((global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem)(base.BaseGet(((object)(key)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace EditorsTeamTV.Scheduling.Configuration
{
    
    
    /// <summary>
    /// A collection of QuartzConfigurationItem instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::EditorsTeamTV.Scheduling.Configuration.QuartzThreadPoolSettings.QuartzConfigurationItemPropertyName)]
    public partial class QuartzThreadPoolSettings : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string QuartzConfigurationItemPropertyName = "quartzConfigurationItem";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override string ElementName
        {
            get
            {
                return global::EditorsTeamTV.Scheduling.Configuration.QuartzThreadPoolSettings.QuartzConfigurationItemPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::EditorsTeamTV.Scheduling.Configuration.QuartzThreadPoolSettings.QuartzConfigurationItemPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem)(element)).Key;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem this[int index]
        {
            get
            {
                return ((global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> with the specified key.
        /// </summary>
        /// <param name="key">The key of the <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem this[object key]
        {
            get
            {
                return ((global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem)(base.BaseGet(key)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="quartzConfigurationItem">The <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public void Add(global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem quartzConfigurationItem)
        {
            base.BaseAdd(quartzConfigurationItem);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="quartzConfigurationItem">The <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public void Remove(global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem quartzConfigurationItem)
        {
            base.BaseRemove(this.GetElementKey(quartzConfigurationItem));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem GetItemAt(int index)
        {
            return ((global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> with the specified key.
        /// </summary>
        /// <param name="key">The key of the <see cref="global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem GetItemByKey(string key)
        {
            return ((global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem)(base.BaseGet(((object)(key)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace EditorsTeamTV.Scheduling.Configuration
{
    
    
    /// <summary>
    /// The QuartzConfigurationItem Configuration Element.
    /// </summary>
    public partial class QuartzConfigurationItem : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Key Property
        /// <summary>
        /// The XML name of the <see cref="Key"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string KeyPropertyName = "key";
        
        /// <summary>
        /// Gets or sets the Key.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Key.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem.KeyPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public string Key
        {
            get
            {
                return ((string)(base[global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem.KeyPropertyName]));
            }
            set
            {
                base[global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem.KeyPropertyName] = value;
            }
        }
        #endregion
        
        #region Value Property
        /// <summary>
        /// The XML name of the <see cref="Value"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string ValuePropertyName = "value";
        
        /// <summary>
        /// Gets or sets the Value.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Value.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem.ValuePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public string Value
        {
            get
            {
                return ((string)(base[global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem.ValuePropertyName]));
            }
            set
            {
                base[global::EditorsTeamTV.Scheduling.Configuration.QuartzConfigurationItem.ValuePropertyName] = value;
            }
        }
        #endregion
    }
}
